### ISSUE TITLE
Table Job Journal Line (210)

### ISSUE THREAD

**Issue by totomakers** [naviwest/dynamics-api#5]
Permet d'obtenir les Job Journal Line d'une feuille spécifique et d’effectuer
- Create
- Read
- Delete

- [x] `GET /journal/{Journal Template Name}/{Journal Batch Name}` 
Retourne les lignes spécifiques a la feuille

- [x] `GET /journal/{Journal Template Name}/{Journal Batch Name}/{id}` 
Affiche plus d'informations sur une ligne détaillée

- [x] `DELETE /journal/{Journal Template Name}/{Journal Batch Name}/{id}` 
Supprime la ligne spécifique

- [ ] `POST /journal/{Journal Template Name}/{Journal Batch Name}/` 
Créer une nouvelle ligne dans le journal

Les règles de validation pour la nouvelle ligne sont a définir 👍  

**Pensez au commentaire liée a la ligne..**

**Comment by MaximeDawn** [comment]
TODO : Modifier la fonction d'ajout de ligne pour retirer toutes les valeurs par défaut inutiles.
